Fix:-Documentation typo fixes
PalisadoesFoundation/talawa-docs pull request #335
Opened 2023-03-07 05:47 UTC by Biki-das

fix #327 

I have installed a third party plugin to scan for typos . so it listed out the possible one, if anyone find other typos they can fix them referring the same issue i created

2023-03-07 13:17 UTC, palisadoes approved these changes

2023-03-07 13:22 UTC, palisadoes requested changes
Please make the changes requested.

2023-03-07 13:22 UTC, palisadoes commented on docs/developers/talawa-admin/introduction.md
> +- These shows list of active `Events` in the organization.
`These show a list`

2023-03-07 13:22 UTC, palisadoes commented on docs/features/members/preapprovals.md
> + Note: Ideally the QR code should contain all the organizations API login information so that it doesn&#39;t need to be re keyed.
`re-keyed`

2023-03-07 13:22 UTC, palisadoes commented on docs/features/members/roles.md
> +1. **Members need to be assigned roles :** in order to provide a tailored an experience for each user so that application features are not arbitrarily available to all users of the application
`a tailored experience`

2023-03-07 13:23 UTC, palisadoes commented
What package did you use to do this? We can ask someone to automate the processing with each pull request and get a overall higher quality of documentation. @tasneemkoushar @evasharma12 @anwersayeed

2023-03-07 14:27 UTC, Biki-das commented
@palisadoes thanks for the quick review!

2023-03-07 14:43 UTC, palisadoes commented
What package did you use for this? We need to get it integrated with our workflows. A manual process isn't sustainable.

2023-03-07 14:45 UTC, Biki-das commented
> What package did you use for this? We need to get it integrated with our workflows. A manual process isn't sustainable.

https://github.com/streetsidesoftware/vscode-spell-checker , this is the one i used!

2023-03-07 14:56 UTC, evasharma12 commented
> What package did you use to do this? We can ask someone to automate the processing with each pull request and get a overall higher quality of documentation. @tasneemkoushar @evasharma12 @anwersayeed

@palisadoes We didn't use any package for spell check or any typo mistakes. But using a package to automate this process with each PR might create problem. There are some technical or code related words which might not pass with the spell check. So I think we can use some package to only highlight the errors and let the writer/coder handle them manually.

2023-03-07 14:57 UTC, Biki-das commented
> > What package did you use to do this? We can ask someone to automate the processing with each pull request and get a overall higher quality of documentation. @tasneemkoushar @evasharma12 @anwersayeed
> 
> @palisadoes We didn't use any package for spell check or any typo mistakes. But using a package to automate this process with each PR might create problem. There are some technical or code related words which might not pass with the spell check. So I think we can use some package to only highlight the errors and let the writer/coder handle them manually.

the spell checker sometime catches word which are not typos, so i agree on this , adding it as a PR filter might lead to problems!

2023-03-07 15:06 UTC, palisadoes approved these changes

2023-03-07 15:06 UTC, merged

2023-03-27 14:01 UTC, Biki-das commented
> > What package did you use to do this? We can ask someone to automate the processing with each pull request and get a overall higher quality of documentation. @tasneemkoushar @evasharma12 @anwersayeed
> 
> @palisadoes We didn't use any package for spell check or any typo mistakes. But using a package to automate this process with each PR might create problem. There are some technical or code related words which might not pass with the spell check. So I think we can use some package to only highlight the errors and let the writer/coder handle them manually.

@evasharma12 we can add those technical words as a list of valid words in a config file and then run the Gh workflow, this is a more better work flow

cc @palisadoes