Feat:-Fixed edit url option to redirect to the corresponding page
PalisadoesFoundation/talawa-docs pull request #386
Opened 2023-03-08 18:42 UTC by Biki-das

#385

2023-03-08 18:43 UTC, palisadoes commented
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. I greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

2023-03-08 18:46 UTC, Biki-das commented
> Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.
> 
> Please also fill in the template for the pull request as completely as you can. I greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

Sure will keep that in mind for the next subsequent of my work.

2023-03-08 19:56 UTC, palisadoes commented
Please fix it now. The importance is equal for existing and future pull requests.

2023-03-08 23:27 UTC, palisadoes requested changes
1. You have hard coded the https://github.com/PalisadoesFoundation/talawa-docs/edit/develop/docs/ URL.
1. This will mean clicking on the link will edit the Palisadoes Foundation organization's GitHub repo files directly. This means that the person editing will need to have web edit rights to the repository. As I told you in the issue:
     1. These persons would be authorized users of the repository, given special rights as contributors.
     2. We want all edits to the Palisadoes Foundation Talawa-Docs to be peer reviewed through PRs.

You gave the impression that the URL would direct people to their own personal copy of the repo. 

As it stands the PR and issue need to be closed

2023-03-08 23:29 UTC, palisadoes commented
Closing

2023-03-09 03:41 UTC, Biki-das commented
> 1. You have hard coded the https://github.com/PalisadoesFoundation/talawa-docs/edit/develop/docs/ URL.
> 
>     2. This will mean clicking on the link will edit the Palisadoes Foundation organization's GitHub repo files directly. This means that the person editing will need to have web edit rights to the repository. As I told you in the issue:
>        
>        1. These persons would be authorized users of the repository, given special rights as contributors.
>        2. We want all edits to the Palisadoes Foundation Talawa-Docs to be peer reviewed through PRs. This is very important.
> 
> 
> In my haste, I didn't realize that the URL would direct people to Palisadoes, and thought it would redirect them to their own personal copy of the repo.
> 
> As it stands the PR and issue need to be closed. Closing.

@palisadoes I might have failed to explain you properly , Let me again explain what the `edit this Page` option would do ,as it seems there is some misalignment on your behalf.
In no case anyone would be able to edit the docs directly, that is not how it works, instead this would generate a path to create a new PR req everytime somone wants to edit some change , if someone does not have the Fork yet, they will get a prompt to fprk it and then apply the changes and then creating a PR as they would create for every change they wanted to do in a normal situation.

Hope i was able to explain, looking forward to your thoughts!

2023-03-09 12:30 UTC, palisadoes approved these changes

2023-03-09 12:30 UTC, merged