Added outreachy internship
PalisadoesFoundation/talawa-docs pull request #442
Opened 2023-03-10 19:20 UTC by babygirl2000

**I added outreachy internship to the internship section of the website**
1. I introduced outreachy and briefly outlined what it is about and included a link to the outreachy website
2. I mentioned the different Talawa projects that are part of the outreachy internship with links to the github repositories
3. I added a getting-started page where i outlined the different files applicants should read through to understand how to contribute
4. Some links to different parts of the website were included and also a link to the slack channel

**Issue Number:**

Fixes #396

2023-03-10 21:40 UTC, palisadoes requested changes
You never know what you missed until you get it. Thanks.
Please make the necessary changes.

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/getting-started.md
> +7. **README.md**
1. Please put this as the first point
2. Mention as a bullet that people can join our slack channel by following the link on the README.md file of the Talawa repo

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/getting-started.md
> +1. **CODE_OF_CONDUCT.md**
1. Create an H2 title `Important Files` then...
1. Make each of these bullets H3 titles under that

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/getting-started.md
> +## Getting started with our repositories
1. Capitalize each word
1. Add introductory text beneath the title.

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/getting-started.md
> +1. [Talawa mobile github](https://github.com/PalisadoesFoundation/talawa)
Add a space above. Sometimes markdown requires that for bullets to be recognised.

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/getting-started.md
> +1. [Talawa Docs github](https://github.com/PalisadoesFoundation/talawa-docs).
Add a closing sentence below the bullets. It makes the ending less abrupt

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/introduction.md
> +Inorder to be part of outreachy internship,
Please add  a link to the criteria. That way we won't have to maintain it if they change. Reduce the amount of text to match. Add the link to the section below.

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/introduction.md
> +### some useful links
Capitalize

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/contribution.md
> +1. Open a pull request(PR)
Add a closing sentence after these and any other bullets in the PR. It makes the flow better.

2023-03-10 21:40 UTC, palisadoes commented on docs/internships/outreachy/contribution.md
> +1. Talawa-API
Add a space above.

2023-03-11 02:05 UTC, babygirl2000 commented
> You never know what you missed until you get it. Thanks. Please make the necessary changes.
Thank you for the review I will make the necessary changes.

2023-03-11 16:57 UTC, palisadoes approved these changes

2023-03-11 16:57 UTC, palisadoes commented on docs/internships/outreachy/introduction.md
> +here are some links to get you started
Capitalize H

2023-03-11 16:57 UTC, merged

2023-03-11 19:15 UTC, babygirl2000 commented
Thank you very much :)