fix: inconsistency in the user interface
PalisadoesFoundation/talawa-docs pull request #481
Opened 2023-03-13 11:52 UTC by faveee

**What kind of change does this PR introduce?**
Refactoring

**Issue Number:** #411 

Fixes #411 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
Nil

**If relevant, did you update the documentation?**
Yes, i did

**Summary**
This was observed while going through the web page. Although seemingly small, it doesn't look decent for a professional website. The disparity is so glaring that it gives the web page an amateur feel thereby defacing the overall design of the website.

**Does this PR introduce a breaking change?**
No, it doesn't

**Other information**
Nil

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

2023-03-13 13:02 UTC, Cioppolo14 commented on docs/developers/talawa-api/expectations.md
> +> This page provides an in overview to what is expected from the Talawa API thereby increasing productivity and improving the application.
Please remove the word "in", and break this into two sentence. The second one beginning with, "Thereby,"

2023-03-13 13:03 UTC, Cioppolo14 commented on docs/developers/talawa-api/mutations.md
> +This doucument outlines our mutations and to which type of user each is constrained. Common types of mutations include insertions and deletions among others. Insertions are new changes to the Talawa
Please fix the legacy error in the spelling of document.  Please remove the words "among others"

2023-03-13 13:04 UTC, Cioppolo14 requested changes
Thank for your this submission! I have a few editorial comments before we're ready to merge.

2023-03-14 14:25 UTC, faveee commented
Thank you for the feedback @Cioppolo14 . I apologise for the late response. I've added the requested changes, awaiting your review!

2023-03-17 09:03 UTC, faveee commented on docs/developers/talawa-api/expectations.md
> +> This page provides an in overview to what is expected from the Talawa API thereby increasing productivity and improving the application.
@Cioppolo14 Can you kindly review this PR? Thank you!

2023-03-18 00:56 UTC, Cioppolo14 commented
@faveee Can you please resolve the conflicting files?

2023-03-18 01:02 UTC, Cioppolo14 requested changes
Please fix the conflicting files and the one comment on the expectations file.  Thank you!

2023-03-18 01:02 UTC, Cioppolo14 commented on docs/developers/talawa-api/expectations.md
> +> This page provides an overview to what is expected from the Talawa API. Thereby increasing productivity and improving the application.
Please add the word "as" between overview and to.  For example, "This page provides an overview as to what is expected..."

2023-03-20 17:15 UTC, faveee commented
@Cioppolo14 In my bid to resolve the conflicting files I mistakenly closed this PR. Can you please reopen and revert?

I look forward to your response. Thank you

2023-03-20 18:37 UTC, faveee commented
> @faveee Can you please resolve the conflicting files?

Hello! @Cioppolo14 All conflicting files have been resolved.

2023-03-21 03:08 UTC, Cioppolo14 commented on docs/developers/talawa-api/expectations.md
> +> This page provides an in overview to what is expected from the Talawa API thereby increasing productivity and improving the application.
@faveee Please add a , after Thereby

2023-03-21 03:08 UTC, Cioppolo14 commented on docs/developers/talawa-api/mutations.md
> +This doucument outlines our mutations and to which type of user each is constrained. Common types of mutations include insertions and deletions among others. Insertions are new changes to the Talawa
@faveee  Please remove the words "among others"

2023-03-21 03:10 UTC, Cioppolo14 requested changes
Please address my comments I put in the responses to previous comments.

2023-03-21 08:49 UTC, faveee commented
> Please address my comments I put in the responses to previous comments.

I apologize for the back and forth. I erroneously deleted the previous commits and closed the PR in my bid to resolve the conflicting files.

2023-03-22 01:21 UTC, Cioppolo14 approved these changes

2023-03-22 01:24 UTC, palisadoes requested changes
Please make the requested changes

2023-03-22 01:24 UTC, palisadoes commented on docs/developers/talawa-api/mutations.md
> +
1. Please fix this. The >>> indicate a merge conflict. @Cioppolo14 FYI
2. This file should be removed from the PR

2023-03-22 13:16 UTC, faveee commented on docs/developers/talawa-api/mutations.md
> +
@palisadoes Are you requesting for the mutations.md file to be deleted or for the conflict to be resolved? I'm not quite clear on your instruction.

2023-03-22 16:32 UTC, palisadoes approved these changes

2023-03-22 16:32 UTC, merged