Bug Report: Documentation Typo
PalisadoesFoundation/talawa-docs pull request #483
Opened 2023-03-13 15:49 UTC by Yass32

**What kind of change does this PR introduce?**

Bugfix: Fixed typos on about.md and core-functionalities.md

**Issue Number:**

Fixes #426 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

2023-03-13 16:00 UTC, salman-farooqi commented on docs/about.md
> +* An API providing access to data and features
In my opinion (I maybe am wrong):
```suggestion
* A mobile application with social media features.
* A web based portal to be used by the organization’s administrative team, and 
* An API providing access to data and features.
```

2023-03-13 23:24 UTC, Cioppolo14 requested changes
Please resolve the comments below and ensure there are no changes in the index.html.  Thank you!

2023-03-13 23:24 UTC, Cioppolo14 commented on docs/functionalities/core-functionalities.md
> +    1. An Automatic group chat is created for persons within an event
Please remove the capital letter from "Automatic" so it is "An automatic"

2023-03-13 23:24 UTC, Cioppolo14 commented on docs/about.md
> +* An API providing access to data and features
Please incorporate salman-farooqi's changes below.

2023-03-14 08:41 UTC, Yass32 commented
@Cioppolo14 its done, and no i haven't made any changes to index.html

2023-03-18 01:05 UTC, Cioppolo14 commented
> @Cioppolo14 its done, and no i haven't made any changes to index.html

Do you know why the index.html is in your "files changed" list? Can you delete it?

2023-03-18 01:08 UTC, Cioppolo14 requested changes
Please address the comment for about.md and the index.html issue.

2023-03-18 01:08 UTC, Cioppolo14 commented on docs/about.md
> +* A mobile application with social media features.
Please change the period after "social media features" to a comma.

2023-03-20 13:41 UTC, Cioppolo14 commented
@Yass32 Any progress on this?

2023-03-20 17:52 UTC, Yass32 commented
> @Yass32 Any progress on this?

Yes done

2023-03-21 03:21 UTC, Cioppolo14 requested changes
Please ensure that there are no file changes in the index.html file.

2023-03-21 08:35 UTC, Yass32 commented
> Please ensure that there are no file changes in the index.html file.

Ive removed it. is that okay?

2023-03-22 01:32 UTC, Cioppolo14 requested changes
Please remove the styles.css file as well.

2023-03-22 13:18 UTC, Yass32 commented
> Please remove the styles.css file as well.

its done

2023-03-22 18:59 UTC, Cioppolo14 approved these changes

2023-03-22 19:01 UTC, merged