Correct grammar & spelling for internships page
PalisadoesFoundation/talawa-docs pull request #488
Opened 2023-03-13 21:51 UTC by tinniaru3005

**What kind of change does this PR introduce?**
Correct grammar & spelling for internships page

**Issue Number:**

Refers #459 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

2023-03-13 21:58 UTC, tinniaru3005 commented
I am breaking down the PR into smaller parts to avoid merge conflicts. This will also simplify the review process.

2023-03-13 23:37 UTC, Cioppolo14 commented
@tinniaru3005 Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

Please also fix the failing tests. 

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done.

Thank you!

2023-03-14 02:21 UTC, salman-farooqi commented on docs/internships/gsoc/application-process.md
> +In drawing up your proposal you should work with your chosen project community.
In drawing up your proposal you should work with your chosen project's community.

2023-03-14 02:22 UTC, salman-farooqi commented on docs/internships/gsoc/application-process.md
> +In drawing up your proposal you should work with your chosen project community.
```suggestion
In drawing up your proposal you should work with your chosen project's community.
```

2023-03-14 02:30 UTC, salman-farooqi commented on docs/internships/outreachy/getting-started.md
> +The installation guide for the projects can be found in this file. Here, the dependencies to install and the versions, and essential configurations are outlined step by step for different operating s
```suggestion
The installation guide for the projects can be found in this file. Here, the dependencies to install the versions and essential configurations are outlined step by step for different operating systems for applicants to successfully run the projects locally on their machines.
```

2023-03-14 06:11 UTC, tinniaru3005 commented
@Cioppolo14 The issue is about correcting the grammar and spelling for the entire docs website. It involves a lot of files and almost every line. So I wanted to break down it into smaller PRs. This PR is about correcting the internship-related pages. So, I changed the description so that the issue doesn't close. Please let me know if that looks good to you.

2023-03-14 06:12 UTC, tinniaru3005 commented
Also, I have filled up the template completely.

2023-03-14 13:35 UTC, Cioppolo14 commented
@tinniaru3005 Thanks for updating the PR. Please address these items:
-  I'm okay with leaving this PR as one since they're all editoral changes, so I will leave that up to you. 
- We still have some failing tests.  Can you please fix those? 
- Please change the PR so it will automatically close the issue. The PR_GUIDELINES.md file has details.

2023-03-14 13:37 UTC, tinniaru3005 commented
@Cioppolo14 can you please help me out in understanding why the tests are failing and how I can solve it.

2023-03-14 13:40 UTC, Cioppolo14 commented
@tinniaru3005 I am looking at it.  Have you confirmed your docusaurus is the same version used on Talawa Docs?

2023-03-15 13:04 UTC, Cioppolo14 requested changes
Please let me know if updating Docusaurus fixes the test errors.

2023-03-15 13:07 UTC, tinniaru3005 commented
How can I find out the version of docusaurus? Can you please guide me like change to which file can fix this

2023-03-15 18:33 UTC, tinniaru3005 commented
@Cioppolo14 I am trying to see how to solve the issue. If nothing works I will close the PR. I will start reworking and make small commits and draft a PR. I guess that will help me understand better where the problem is coming from. Please let me know if you can think of any other way I can fix the failing tests.

2023-03-16 19:20 UTC, noman2002 commented
@tinniaru3005 Please fix the conflicting files.

2023-03-17 17:24 UTC, tinniaru3005 commented
> @tinniaru3005 Please fix the conflicting files.

Sure I will fix them. Can you please help me figure out why the tests are failing? I tried understanding the error messages but couldn't figure out how to resolve them. Otherwise, I am considering closing this PR and opening a new one with smaller commits. That will probably help me better understand how to fix it. Can you please tell me if that's fine or if should I consider some other approach?

2023-03-18 00:33 UTC, Cioppolo14 commented
@tinniaru3005 Some questions to help:
1) Are you using the yarn.lock file from here: https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/yarn.lock  ? 
2) The conflicting files probably have new versions from other PRs, so please make sure you are using the latest version. 
3) Are you using Docusaurus version 2.3.1, the latest stable version?

2023-03-18 13:48 UTC, tinniaru3005 commented
Thanks a lot @Cioppolo14, I am looking into it.

2023-03-22 19:03 UTC, Cioppolo14 commented
@tinniaru3005 Can you resolve the conflicting files?

2023-03-22 19:15 UTC, tinniaru3005 commented
> @tinniaru3005 Can you resolve the conflicting files?

Sure @Cioppolo14, I am doing it in a few hours. Got a bit busy with writing the proposal. Thanks a lot for your patience and also for reminding me. :)

2023-03-23 16:39 UTC, tinniaru3005 commented
@Cioppolo14 I have solved the merge conflicts. Thanks again for reminding me on that :)

2023-03-24 14:46 UTC, Cioppolo14 commented
@tinniaru3005 I'm still seeing two conflicting files, really just ideas.md. Can you address this?

2023-03-24 15:02 UTC, tinniaru3005 commented
@Cioppolo14 I solved it :)

2023-03-24 15:05 UTC, tinniaru3005 commented
@Cioppolo14 I tried checking the possibilities to why the tests are failing but couldn't figure it out. The other PR #429  that I raised worked fine, though.

2023-03-28 00:24 UTC, Cioppolo14 commented
@tinniaru3005 There were some significant changes to the website yesterday, can you address the conflicting files?

2023-03-28 00:29 UTC, Cioppolo14 commented
We've had significant changes to the page, and we'd like to pause grammar and spelling changes for now, so I am going to close this PR and the related issue.

2023-03-28 00:29 UTC, closed without merging