added section for explaining stack choice of talawa (updated)
PalisadoesFoundation/talawa-docs pull request #515
Opened 2023-03-16 12:08 UTC by lonereaper

What kind of change does this PR introduce?

Added to the "Applications" page information on why talawa uses typescript, flutter, and monogodb in their projects

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-docs/issues/450

Did you add tests for your changes?

No

**Snapshots/Videos:**
<img width="501" alt="1" src="https://user-images.githubusercontent.com/39475669/225612279-e79ad60c-9229-478c-8fc5-ed1b2c9ddc86.png">
<img width="494" alt="2" src="https://user-images.githubusercontent.com/39475669/225612286-cb208fa7-7f87-4d02-b088-c7ae2c6fecc3.png">
<img width="478" alt="3" src="https://user-images.githubusercontent.com/39475669/225612291-982cc793-8689-4909-a53b-6605e506d265.png">

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

yes

2023-03-16 13:05 UTC, Cioppolo14 commented
@lonereaper Please update to the latest version of Docusaurus and remove yarn.log.  I believe that is why the tests are failing. Thank you.

2023-03-16 13:26 UTC, lonereaper commented
i have updated Docusaurus and removed yarn.log from my fork is it working now ?

> @lonereaper Please update to the latest version of Docusaurus and remove yarn.log. I believe that is why the tests are failing. Thank you.

2023-03-16 13:31 UTC, SalilHarit commented
i fixed it 

> @lonereaper Please update to the latest version of Docusaurus and remove yarn.log. I believe that is why the tests are failing. Thank you.

2023-03-16 19:12 UTC, noman2002 commented
@lonereaper Please fix the failing test.

2023-03-17 05:12 UTC, palisadoes requested changes
The only file that should be submitted are markdown files. No other files should be included. Please remove  `.gitignore` and `yarn.lock` from the PR.

2023-03-17 05:12 UTC, palisadoes commented on .gitignore
> +yarn.lock*
This absolutely needs to remain. Remove this immediately or else Docusaurus will fail to run for everyone else. Revert this. You need to upgrade to the latest version of Docusaurus.

2023-03-17 06:38 UTC, palisadoes requested changes
Only the markdown file should get in there PR. Delete all the other ones. They are out of scope

2023-03-18 18:29 UTC, CyberWake commented
@lonereaper please resolve the conflicts

2023-03-19 13:49 UTC, Cioppolo14 commented
@lonereaper Can you address why it is showing over 5000 files changed?

2023-03-19 13:57 UTC, lonereaper commented
> @lonereaper Can you address why it is showing over 5000 files changed?

i was asked to remove .gitignore and then vscode pushed the nodemodules to commit because of it

2023-03-19 18:21 UTC, closed without merging