this addresses the previous fix for showing 5k+ files and
PalisadoesFoundation/talawa-docs pull request #536
Opened 2023-03-19 18:33 UTC by lonereaper

What kind of change does this PR introduce?

Added to the "Applications" page information on why talawa uses typescript, flutter, and monogodb in their projects

Issue Number:

Fixes #450 

Did you add tests for your changes?

No

Snapshots/Videos:
<img width="501" alt="1" src="https://user-images.githubusercontent.com/39475669/226199065-78882fbe-30f9-4307-938f-7161afdb35a2.png">
<img width="494" alt="2" src="https://user-images.githubusercontent.com/39475669/226199067-a7e23314-55bf-467f-ad32-01c27fc157f8.png">
<img width="478" alt="3" src="https://user-images.githubusercontent.com/39475669/226199069-3c540374-0c88-4aef-90db-351adddc764d.png">

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

no
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**

Yes

2023-03-19 23:08 UTC, Cioppolo14 commented on docs/applications/architecture.md
> +Why is it Important ?
can you change the I in Important to lowercase (i)?

2023-03-19 23:08 UTC, Cioppolo14 commented on docs/applications/architecture.md
> +Overall, choosing the right technology stack for a web development project can help ensure that the project meets its requirements, is developed quickly and efficiently, is scalable, well-supported,
Add a . after affordable.

2023-03-22 12:51 UTC, Cioppolo14 requested changes
Can you discuss in the sections why Talawa specifically these?

2023-03-22 13:20 UTC, SalilHarit commented
> Can you discuss in the sections why Talawa specifically these?

sure ! i've had a doubt for quite a while which prevented me from going specific like when we talk about talawa in the terms of used technologies in their project does it mean all of their projects like api ,mobile app and web portal or just mobile app

2023-03-22 15:34 UTC, lonereaper commented
> Can you discuss in the sections why Talawa specifically these?

i've discussed where different technologies are used in different places using examples is it enough ?

2023-03-22 18:13 UTC, Cioppolo14 approved these changes

2023-03-22 18:14 UTC, merged