Update: Add installation.md file
PalisadoesFoundation/talawa-docs pull request #575
Opened 2023-03-25 16:26 UTC by Vic-Orlands

**What kind of change does this PR introduce?**
A bug.

**Issue Number:** #419

Fixes #419 

**Summary**
The talawa, talawa-admin and talawa-api repositories all have a standardized README.md file that refers to their respective INSTALLATION.md and CONTRIBUTING.md files. This is not the case with talawa-docs. 

Also, many slack channel contributors kept asking questions about the installation. This is because npm produces an error page when you run the server locally. I took account of this bug when fixing the issue.

**Solution**
I converted the README.md file to more closely match those of the other repositories. I created a table of content to show the steps and easily jump to the various sections.

Lastly, I removed any and all npm information that were redundant and replaced them with yarn.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/CONTRIBUTING.md)?**
Yes

2023-03-28 00:53 UTC, Cioppolo14 requested changes
This PR should also change the README.md file to remove the installation information placed with installation.md.

2023-03-30 07:23 UTC, Vic-Orlands commented
> This PR should also change the README.md file to remove the installation information placed with installation.md.

I have removed the installation information from the README.md file

2023-03-30 17:33 UTC, tasneemkoushar approved these changes

2023-03-30 23:31 UTC, Cioppolo14 approved these changes

2023-03-30 23:32 UTC, merged